In [1]:
import ase.db
import ase.io
from ase.md.contour_exploration import ContourExploration
import numpy as np
from relaxation import relax_structure

In [2]:
db = ase.db.connect('structures.db')

In [3]:
db.get(id=1).key_value_pairs

{'hash': 'e04e48aee1ce94c5940c16bb7886952f', 'type': 'ev'}

In [4]:
id_1 = 1335
xtl_1 = db.get_atoms(id=id_1)

In [5]:
relax_structure(xtl_1, steps=20, fmax=0.05)
print(xtl_1.get_positions())
print(xtl_1.get_potential_energy())

      Step     Time          Energy         fmax
BFGS:    0 11:38:43      -33.407323       18.1465
BFGS:    1 11:38:43      -43.048713        6.1120
BFGS:    2 11:38:43      -45.462762        3.8767
BFGS:    3 11:38:43      -47.776815        4.8086
BFGS:    4 11:38:43      -48.837090        3.6238
BFGS:    5 11:38:43      -49.594682        2.4056
BFGS:    6 11:38:43      -50.803555        2.3694
BFGS:    7 11:38:43      -51.172978        2.0118
BFGS:    8 11:38:43      -51.533611        2.3005
BFGS:    9 11:38:43      -51.889408        1.6710
BFGS:   10 11:38:43      -52.284674        2.2713
BFGS:   11 11:38:43      -52.601101        3.2346
BFGS:   12 11:38:43      -53.058613        3.1151
BFGS:   13 11:38:43      -53.578445        2.3248
BFGS:   14 11:38:43      -53.860204        1.4532
BFGS:   15 11:38:43      -54.025981        0.9587
BFGS:   16 11:38:43      -54.219442        1.1179
BFGS:   17 11:38:43      -54.399364        1.4402
BFGS:   18 11:38:43      -54.317697        3.2805
B

In [6]:
maxstep=2
angle_limit=30
starting_energy = xtl_1.get_potential_energy()

dyn=ContourExploration(xtl_1, 
                       maxstep=maxstep,
                       angle_limit=angle_limit, 
                       remove_translation=True,
                       trajectory='xtl_1_{}_{}_notranslation_potentiostat.traj'.format(maxstep, angle_limit),
                       append_trajectory=True,
                       logfile='contour_{}_{}_{}_notranslation_potentiostat.log'.format(maxstep, angle_limit, id_1)
                      )
#dyn.run(20)

for energy_step in np.linspace(0, 1, 20):
    dyn.energy_target=starting_energy + energy_step*xtl_1.get_global_number_of_atoms()
    dyn.run(1)
    #xtl_1.write('structures/{}_{}_{}_{}_notranslation.cif'.format(maxstep, angle_limit, id_1, energy_step))

In [7]:
print(xtl_1.get_positions())
print(xtl_1.get_potential_energy())

[[4.99538459 5.25806274 2.63031449]
 [1.99355409 0.02770307 2.1976636 ]
 [0.50207267 6.17093956 0.55474784]
 [3.65871373 4.04939682 5.86579804]
 [3.13565602 2.89749019 4.18263102]
 [2.41630559 5.69627836 5.60546444]
 [4.71618464 0.34798185 4.88801786]
 [1.91925906 2.02577086 0.87140415]
 [1.13198135 1.45874995 4.70356922]
 [4.01489881 1.0615325  2.06422657]
 [0.94735526 4.10669275 3.08236811]
 [0.26305516 3.13493315 0.89235499]
 [5.12605882 2.74207262 5.05936727]
 [3.37741514 3.43557915 1.99720458]]
-38.82634988699167
